services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:slim
    container_name: openwebui
    restart: unless-stopped
    ports:
      - "3100:8080"
    volumes:
      - openwebui_data:/app/backend/data
volumes:
  openwebui_data:
    name: openwebui_data