services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:slim
    container_name: openwebui
    restart: unless-stopped
    ports:
      - "3100:8080"
    volumes:
      - open-webui_data:/app/backend/data
volumes:
  open-webui_data:
    name: open-webui_data