services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: ${HOSTNAME}
    restart: unless-stopped
    network_mode: host
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_ROUTES=${TS_ROUTES}
      - TS_ACCEPT_DNS=true
      - TS_HOSTNAME=${HOSTNAME}
    volumes:
      - ./tailscale_data:/var/lib/tailscale
      - ./tailscale_tmp:/tmp
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/var/run/tailscale/tailscaled.sock &
        sleep 2
        tailscale up --authkey=${TS_AUTHKEY} --advertise-routes=${TS_ROUTES} --accept-dns --hostname=${HOSTNAME}
        wait