services:
  snmp-exporter:
    image: prom/snmp-exporter:latest
    container_name: snmp-exporter-qnap
    restart: unless-stopped
    ports:
      - "9116:9116"
    volumes:
      - ./config/snmp.yml:/etc/snmp_exporter/snmp.yml:ro
    command:
      - '--config.file=/etc/snmp_exporter/snmp.yml'
    networks:
      - monitoring

networks:
  monitoring:
    name: monitoring
    external: true